/**
 * 權限代碼枚舉
 * 對應 userPermission.json 中的 claims.code
 */
export enum ClaimCode {
    // ========================================
    // 基礎系統
    // ========================================
    BASIC_SYSTEM_MODULE = 'BASIC_SYSTEM_MODULE',
    BASIC_SYSTEM_LOG = 'BASIC_SYSTEM_LOG',
    BASIC_SYSTEM_DIRECTORY = 'BASIC_SYSTEM_DIRECTORY',
    BASIC_SYSTEM_PERMISSION = 'BASIC_SYSTEM_PERMISSION',
    BASIC_SYSTEM_LOG_VIEW = 'BASIC_SYSTEM_LOG_VIEW',
    BASIC_SYSTEM_LOG_EXPORT = 'BASIC_SYSTEM_LOG_EXPORT',

    // ========================================
    // 外部系統
    // ========================================
    EXTERNAL_SYSTEM_MODULE = 'EXTERNAL_SYSTEM_MODULE',
    EXTERNAL_SYSTEM_VENDOR_DATA = 'EXTERNAL_SYSTEM_VENDOR_DATA',
    EXTERNAL_SYSTEM_VENDOR_INTEGRATION = 'EXTERNAL_SYSTEM_VENDOR_INTEGRATION',
    EXTERNAL_SYSTEM_VENDOR_CREATE = 'EXTERNAL_SYSTEM_VENDOR_CREATE',
    EXTERNAL_SYSTEM_VENDOR_EDIT = 'EXTERNAL_SYSTEM_VENDOR_EDIT',

    // ========================================
    // 金流系統
    // ========================================
    PAYMENT_SYSTEM_MODULE = 'PAYMENT_SYSTEM_MODULE',
    PAYMENT_SYSTEM_METHOD = 'PAYMENT_SYSTEM_METHOD',
    PAYMENT_SYSTEM_INTEGRATION = 'PAYMENT_SYSTEM_INTEGRATION',
    PAYMENT_SYSTEM_METHOD_CREATE = 'PAYMENT_SYSTEM_METHOD_CREATE',

    // ========================================
    // 路邊停車系統
    // ========================================
    PARKING_SYSTEM_MODULE = 'PARKING_SYSTEM_MODULE',
    PARKING_SYSTEM_ORDER = 'PARKING_SYSTEM_ORDER',
    PARKING_SYSTEM_REPORT = 'PARKING_SYSTEM_REPORT',
    PARKING_SYSTEM_REPORT_VOID = 'PARKING_SYSTEM_REPORT_VOID',
    PARKING_SYSTEM_REPORT_BILLING = 'PARKING_SYSTEM_REPORT_BILLING',
    PARKING_SYSTEM_REPORT_UPLOAD = 'PARKING_SYSTEM_REPORT_UPLOAD',
    PARKING_SYSTEM_ORDER_CREATE = 'PARKING_SYSTEM_ORDER_CREATE',
    PARKING_SYSTEM_ORDER_CANCEL = 'PARKING_SYSTEM_ORDER_CANCEL',
    PARKING_SYSTEM_REPORT_EXPORT = 'PARKING_SYSTEM_REPORT_EXPORT',
}
